name: docker-build-push-normal-alpine

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: "/normal-alpine.dockerfile"
            tag: "latest"
          - dockerfile: "/rpi-alpine.dockerfile"
            tag: "rpi-latest"
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ${{matrix.dockerfile}}
          push: true
          tags: redbeard2/eisbude:${{matrix.tag}}
